Repository codeit-sprint-part2-2team/rolling, pull requests merged in 2024-11, with the labels that each got.

#175 #146 롤링 페이퍼 생성 페이지
  src/components/BackgroundSelector/BackgroundSelector.jsx
  src/components/BackgroundSelector/RadioCard.jsx
  src/components/BackgroundSelector/RadioCard.styles.js
  src/components/TextField/Input.jsx
  src/hooks/useInputValidation.js
  src/pages/MessagesAdd/MessagesAddPage.jsx
  src/pages/RecipientsAdd/RecipientsAddPage.jsx
Labels: 💄 스타일, ✨ 신규 기능, 📁 컴포넌트

#185 #171 멘토링 수정 사항반영
  src/pages/RecipientsList/RecipientsList.jsx
  src/pages/RecipientsList/RecipientsListPage.jsx
Labels: 💫 업데이트

#186 #172 list 페이지 작업
  src/components/BackgroundSelector/RadioCard.jsx
  src/components/Badge/EmojiBadge.styles.js
  src/components/TabToggle/TabToggle.styles.js
  src/components/TextField/TextField.jsx
  src/components/TotalMessage/TotalMessage.styles.js
  src/pages/RecipientsList/RecipientsCard.jsx
  src/pages/RecipientsList/RecipientsCard.styles.js
  src/pages/RecipientsList/RecipientsList.jsx
  src/pages/RecipientsList/RecipientsList.styles.js
  src/pages/RecipientsList/RecipientsListPage.jsx
  src/pages/RecipientsList/recipientsListPage.module.css
Labels: 📰 페이지

#179 ✨ 삭제 기능 컴포넌트
  src/components/Delete/DeleteClick.jsx
  src/components/MessagesCardList/MessageCardList.jsx
Labels: 🚫 잘못된 이슈, ✨ 신규 기능, ⏸️ 보류, 📁 컴포넌트

#189 #168 메세지 추가하기 페이지 스타일 요소 dom 접근 에러
  .env
  package-lock.json
  package.json
  src/components/TextField/TextEditor.jsx
  src/pages/MessagesAdd/MessagesAddPage.jsx
Labels: 🐛 버그, ♻️ 리팩토링, 📦 패키지

#159 ✨ Simplebanner 이모지 선택기능 추가
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icon-stoke.svg
  src/components/Outlined/Outlined.styles.js
  src/layout/Emoji/EmojiPickerComponent.jsx
  src/layout/Emoji/EmojiPickerComponent.module.css
  src/layout/Emoji/EmojiPickerComponent.styles.js
Labels: ✨ 신규 기능

#192 #191 애로우버튼 블러,투명도 적용
  src/components/ArrowButton/ArrowButton.styles.js
Labels: 💄 스타일

#193 #190 롤링 생성은 완료했으나 폰트로 적용되지않는 이슈
  .cspell.json
  src/components/MessagesCardList/MessageCard.jsx
  src/components/MessagesCardList/MessageCard.styles.js
  src/styles/GlobalStyles.js
Labels: 💄 스타일, ✨ 신규 기능, 💫 업데이트

#211 #205 이모지 클릭 시 해당 id 데이터에 삭제,추가,업데이트 진행
  .cspell.json
  src/App.jsx
  src/components/Badge/EmojiBadge.jsx
  src/components/Badge/EmojiBadge.styles.js
  src/layout/Emoji/EmojiPickerComponent.jsx
  src/layout/Emoji/EmojiPickerComponent.module.css
  src/layout/Emoji/EmojiPickerComponent.styles.js
  src/layout/Emoji/useEmojiManager.js
  src/pages/MessagesList/MessagesListPage.jsx
  src/service/api.js
Labels: ✨ 신규 기능, ♻️ 리팩토링, 📡 API, 🔄 커스텀 훅

#210 #196 수정하기 페이지 기능 구현
  src/components/MessagesCardList/MessageCardList.jsx
  src/components/TextField/TextEditor.jsx
  src/pages/MessagesAdd/MessagesAddPage.jsx
Labels: ✨ 신규 기능

#165 #143 ✨ 헤더 레이아웃 작업
  src/components/Outlined/Outlined.styles.js
  src/layout/Header/MainHeader.jsx
  src/layout/Header/MainHeader.styles.js
  src/pages/HomePage/HomePage.jsx
  src/styles/theme.js
Labels: 📁 컴포넌트

#212 #208 components input file메시지 생성 프로필 선택
  src/components/InputFile/InputFile.jsx
  src/components/InputFile/InputFile.module.css
  src/components/InputFile/InputFile.styles.js
Labels: 💄 스타일, ♻️ 리팩토링

#219 #218 input 입력된 상태에서 뒤로가기 클릭 시 확인 팝업
  src/hooks/useConfirmExit.js
  src/pages/MessagesAdd/MessagesAddPage.jsx
  src/pages/RecipientsAdd/RecipientsAddPage.jsx
Labels: ✨ 신규 기능, 🔄 커스텀 훅

#214 #197 pages messages add메세지 생성
  src/pages/MessagesAdd/MessagesAddPage.jsx
  src/pages/MessagesAdd/MessagesAddPage.module.css
  src/pages/MessagesAdd/MessagesAddPage.styles.js
  src/pages/RecipientsAdd/RecipientsAddPage.jsx
Labels: 💄 스타일, ♻️ 리팩토링

#209 Feature/#153 롤링 simple banner 드롭다운 기능
  .gitignore
  package-lock.json
  src/assets/share-24.svg
  src/components/toast/Toast.Styles.js
  src/components/toast/Toast.jsx
  src/components/toast/ToastMessages.jsx
  src/layout/Emoji/KaKaoShare.js
  src/layout/Emoji/SharingSelector.jsx
  src/layout/Emoji/SharingSelector.module.css
  src/pages/HomePage/HomePage.jsx
Labels: 💄 스타일, ✨ 신규 기능, 💬 논의 필요, 🔨수정해주세요

#226 #223 공통 스타일 속성 제작
  public/index.html
  src/pages/HomePage/HomePage.jsx
  src/pages/MessagesAdd/MessagesAddPage.jsx
  src/pages/MessagesAdd/MessagesAddPage.module.css
  src/pages/MessagesAdd/MessagesAddPage.styles.js
  src/pages/RecipientsAdd/RecipientsAddPage.jsx
  src/pages/RecipientsList/RecipientsListPage.jsx
  src/styles/GlobalStyles.js
  src/styles/common.css
  src/styles/common/Common.styles.js
  src/styles/common/common.md
  src/styles/reset.css
Labels: 💄 스타일, ✨ 신규 기능, ♻️ 리팩토링

#181 Feature/#63 메인 페이지
  src/assets/Home/feat01.svg
  src/assets/Home/feat02.jpg
  src/assets/Home/feat02.png
  src/pages/HomePage/HomePage.jsx
  src/pages/HomePage/HomePage.module.css
  src/pages/HomePage/HomePage.styles.js
Labels: 💄 스타일, ♻️ 리팩토링, 💫 업데이트

#229 🐛 홈페이지 불러와지지 못하는 버그 잡기
  src/pages/HomePage/HomePage.jsx
Labels: 🐛 버그, 🚨 긴급

#227 #221 디자인 시스템 구축
  public/index.html
  src/pages/RecipientsList/RecipientsListPage.jsx
  src/styles/GlobalStyles.js
  src/styles/common.css
  src/styles/common/Common.styles.js
  src/styles/common/common.md
  src/styles/reset.css
Labels: 🫠 중복

#234 🐛 인기순,최신순 에러 수정 코드
  src/pages/RecipientsList/RecipientsListPage.jsx
Labels: 🐛 버그

#213 #198 components background selector롤링페이퍼 생성 배경화면 선택
  src/components/BackgroundSelector/RadioCard.jsx
  src/components/BackgroundSelector/RadioCard.module.css
  src/components/BackgroundSelector/RadioCard.styles.js
Labels: 💄 스타일, ♻️ 리팩토링

#238 #195 헤더 기능 붙이기 작업
  .env
  example.http
  src/App.jsx
  src/components/toast/Toast.Styles.js
  src/layout/Emoji/EmojiDropDown.jsx
  src/layout/Emoji/EmojiDropDown.module.css
  src/layout/Emoji/EmojiPickerComponent.jsx
  src/layout/Emoji/EmojiPickerComponent.module.css
  src/layout/Header/HeaderLayout.jsx
  src/layout/Header/MainHeader.jsx
  src/layout/Header/MainHeader.module.css
  src/layout/Header/MainHeader.styles.js
  src/pages/HomePage/HomePage.jsx
  src/pages/MessagesList/MessagesListPage.jsx
  src/router/Content.jsx
Labels: 📁 컴포넌트

#215 Feature/#194 이모지 드롭다운 데이터 가져와서 보여주기
  src/layout/Emoji/EmojiDropDown.jsx
  src/layout/Emoji/EmojiDropDown.module.css
  src/pages/HomePage/HomePage.jsx
Labels: 💄 스타일, ✨ 신규 기능, 🚨 긴급, 💬 논의 필요

#216 Feature/#202 components tap toggle 탭 토글
  src/components/TabToggle/TabToggle.jsx
  src/components/TabToggle/TabToggle.module.css
  src/components/TabToggle/TabToggle.styles.js
Labels: 🐛 버그, 💄 스타일, ♻️ 리팩토링

#233 #232_component---EmojiBadge
  src/components/Badge/EmojiBadge.jsx
  src/components/Badge/EmojiBadge.module.css
Labels: ♻️ 리팩토링

#241 #204 components messages card list메시지 카드 리스트 컴포넌트
  src/components/CardComponents/Card/Card.jsx
  src/components/CardComponents/Card/Card.styles.js
  src/components/CardComponents/CardAdd/CardAdd.jsx
  src/components/CardComponents/CardAdd/CardAdd.styles.js
  src/components/CardComponents/CardHeader/CardHeader.jsx
  src/components/CardComponents/CardHeader/CardHeader.styles.js
  src/components/CardComponents/ModalCard/ModalCardHeader.jsx
  src/components/CardComponents/ModalCard/ModalCardHeader.styles.js
  src/components/ModalComponents/ModalActions/ModalActions.jsx
  src/components/ModalComponents/ModalActions/ModalActions.styles.js
  src/components/ModalComponents/ModalContent/ModalContent.jsx
  src/components/ModalComponents/ModalContent/ModalContent.styles.js
  src/components/ModalComponents/ModalHeader/ModalHeader.jsx
  src/components/ModalComponents/ModalHeader/ModalHeader.styles.js
  src/components/Shared/Line/Line.jsx
  src/components/Shared/Line/Line.styles.js
  src/hooks/useInputValidation.js
  src/pages/HomePage/HomePage.jsx
  src/pages/MessagesList/MessagesListPage.jsx
  src/styles/common/reset.css
Labels: 💄 스타일, 📁 컴포넌트, 💫 업데이트

#243 #220 관리자 모드 버튼 패스워드로 edit로 이동
  .env
  src/components/CardComponents/CardList/CardList.jsx
  src/pages/MessagesEdit/MessagesEditPage.jsx
Labels: ✨ 신규 기능, 🔒 보안

#252 Feature/#249 edit 이동 시 bg에 header 묻힘
  src/components/CardComponents/CardList/CardList.styles.js
  src/layout/Emoji/EmojiDropDown.jsx
  src/layout/Header/MainHeader.styles.js
  src/pages/MessagesEdit/MessagesEditPage.jsx
  src/pages/MessagesList/MessagesListPage.jsx
Labels: 🐛 버그, 💄 스타일

#253 Feature/#240 헤더 스타일링 수정사항
  src/assets/icon-arrow_down.svg
  src/assets/icon-arrow_top.svg
  src/components/Outlined/Outlined.styles.js
  src/components/TextField/Dropdown.jsx
  src/components/TextField/Dropdown.styles.js
  src/layout/Emoji/EmojiDropDown.jsx
  src/layout/Emoji/EmojiDropDown.module.css
  src/layout/Emoji/SharingSelector.jsx
  src/layout/Header/MainHeader.styles.js
Labels: 💄 스타일, 🔨수정해주세요

#177 📝 ✨ 무한 스크롤 기능 컴포넌트 추가
  SECURITY.md
  src/components/CardComponents/CardAdd/CardAdd.jsx
  src/components/CardComponents/CardAdd/CardAdd.styles.js
  src/components/CardComponents/CardList/CardList.jsx
  src/components/MessagesCardList/MessageCardList.jsx
  src/pages/MessagesEdit/MessagesEditPage.jsx
  src/pages/MessagesList/MessagesListPage.jsx
  src/pages/MessagesList/MessagesListPage.module.css
  src/pages/MessagesList/MessagesListPage.styles.js
Labels: ✨ 신규 기능, 🔍 검토 필요, 🧪 테스트, 📁 컴포넌트

#263 #239 롤링 페이퍼 메시지 생성 로딩 추가
  src/pages/MessagesAdd/MessagesAddPage.jsx
  src/pages/RecipientsAdd/RecipientsAddPage.jsx
Labels: ♻️ 리팩토링

#261 #242_모달,카드 & 디자인 시스템 작업
  src/components/CardComponents/Card/Card.styles.js
  src/components/CardComponents/Card/CardBase.jsx
  src/components/CardComponents/Card/CardBase.styles.js
  src/components/CardComponents/Card/CustomCard.jsx
  src/components/CardComponents/CardContent/CardContent.jsx
  src/components/CardComponents/CardContent/CardContent.styles.js
  src/components/CardComponents/CardHeader/CardHeader.styles.js
  src/components/TextField/Dropdown.jsx
  src/pages/HomePage/Demo.jsx
  src/router/Content.jsx
  src/styles/common/Common.styles.js
  src/styles/common/media.styles.js
Labels: 🫠 중복, 💄 스타일, ✨ 신규 기능, ♻️ 리팩토링, 💫 업데이트

#264 💄 드롭다운 레이아웃 수정하기
  src/components/TextField/CommonInput.styles.js
  src/components/TextField/Dropdown.jsx
  src/components/TextField/Dropdown.module.css
  src/components/TextField/Dropdown.styles.js
Labels: 🐛 버그, ♻️ 리팩토링

#269 #268 파비콘 이미지 추가
  public/favicon.ico
  public/index.html
Labels: 📝 문서

#231 Feature/#200 components toast토스트
  src/App.jsx
  src/components/CardComponents/Card/Card.styles.js
  src/components/CardComponents/CardHeader/CardHeader.jsx
  src/components/toast/Toast.Styles.js
  src/components/toast/Toast.jsx
  src/components/toast/ToastMessages.jsx
  src/layout/Emoji/SharingSelector.jsx
  src/layout/Emoji/SharingSelector.module.css
  src/layout/Header/MainHeader.module.css
  src/pages/HomePage/HomePage.jsx
Labels: 💄 스타일, ♻️ 리팩토링

#273 #272 롤링 페이퍼 생성 페이지 반응형 작업
  src/components/BackgroundSelector/RadioCard.module.css
  src/components/BackgroundSelector/RadioCard.styles.js
Labels: 💄 스타일

#271 #255 ✨ 다크모드토글 헤더연결작업
  jsconfig.json
  src/App.jsx
  src/components/DarkModeToggle/DarkModeToggle.jsx
  src/components/TabToggle/TabToggle.jsx
  src/components/TabToggle/TabToggle.module.css
  src/components/TabToggle/TabToggle.styles.js
  src/layout/Header/HeaderLayout.jsx
  src/layout/Header/MainHeader.jsx
  src/layout/Header/MainHeader.styles.js
  src/router/Content.jsx
Labels: 💄 스타일, ✨ 신규 기능, 📁 컴포넌트

#274 에러 발생 시 화면 구현
  src/components/NotfoundButton/BackButton.jsx
  src/pages/NotFound/NotFoundPage.jsx
  src/pages/NotFound/NotFoundPage.styles.js
Labels: 💄 스타일, ✨ 신규 기능, 📁 컴포넌트

#289 #284 다크모드 로컬 스토리지
  src/App.jsx
  src/components/DarkModeToggle/DarkModeToggle.jsx
  src/layout/Header/MainHeader.jsx
  src/pages/MessagesAdd/MessagesAddPage.jsx
Labels: 💄 스타일, ✨ 신규 기능

#295 #294 메시지 생성 페이지 이동 버튼 클릭 안됨 수정
  src/components/CardComponents/CardAdd/CardAdd.styles.js
Labels: 🐛 버그

#282 Feature/#280 메시지 남긴 사람 수 다크모드
  src/components/TotalMessage/TotalMessage.jsx
  src/components/TotalMessage/TotalMessage.styles.js
Labels: 💄 스타일, ♻️ 리팩토링

#292 ♻️ 에퍼 페이지 추가 수정
  src/components/NotfoundButton/BackButton.jsx
  src/pages/NotFound/NotFoundPage.jsx
  src/pages/NotFound/NotFoundPage.styles.js
Labels: ♻️ 리팩토링

#296 #293 생성하기 수정하기 버튼 모바일에서 position
  src/pages/MessagesAdd/MessagesAddPage.module.css
Labels: 💄 스타일, ♻️ 리팩토링

#276 Feature/#275 url현재 페이지 복사기능
  src/components/CardComponents/ModalCard/ModalCardHeader.styles.js
  src/components/LoadingSpinner/LoadingSpinner.module.css
  src/layout/Emoji/EmojiDropDown.module.css
  src/layout/Emoji/SharingSelector.jsx
  src/pages/HomePage/HomePage.module.css
Labels: ♻️ 리팩토링

#287 Feature/#281 emoji picker 기능스타일수정
  src/assets/icon-stoke.svg
  src/layout/Emoji/EmojiPickerComponent.jsx
Labels: 💄 스타일, ♻️ 리팩토링

#301 Feature/#300 이모지 dropdown 부분 스타일 및 기능 수정
  README.md
  _redirects
  src/components/Badge/EmojiBadge.jsx
  src/components/Badge/EmojiBadge.module.css
  src/components/TextField/Dropdown.jsx
  src/hooks/useClickOutside.js
  src/hooks/useFetchData.js
  src/layout/Emoji/EmojiDropDown.jsx
  src/layout/Emoji/EmojiDropDown.module.css
  src/styles/themes/theme.js
Labels: 💄 스타일, ♻️ 리팩토링

#303 💄 이모지 드롭다운 hover width 간격 조정
  src/components/TextField/Dropdown.styles.js
  src/layout/Emoji/EmojiPickerComponent.jsx
Labels: ♻️ 리팩토링

#305 🐛 모바일에서 관리자모드 오류 수정
  src/components/CardComponents/CardList/CardList.jsx
Labels: 🐛 버그

#309 kakao템플릿커스텀
  .github/workflows/jekyll-gh-pages.yml
  src/layout/Emoji/KaKaoShare.js
Labels: ♻️ 리팩토링

#312 #311_📝 최종 회고
  양정화.md
Labels: 📝 문서

#314 📝 회고록 작성
  김용철.md
Labels: 📝 문서

#318 📝 회고록
  홍현빈.md
Labels: 📝 문서

#319 📝 최종 회고
  신휘철.md
Labels: 📝 문서

#320 Feature/#316 회고록 작성
  김용철.md
  신휘철.md
  양정화.md
  정소망.md
Labels: 📝 문서

#321 # (성우) 회고 작성
  박성우.md
Labels: 📝 문서
