Repository codeit-sprint-part2-2team/rolling, pull requests merged in 2024-10, with the labels that each got.

#4 [#2] 초기 개발 세팅
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/index.js
Labels: 🎉 세팅

#8 [#7] 포멧터 & 패키지 업데이트
  .eslintrc.js
  .vscode/settings.json
  package-lock.json
  package.json
Labels: 🎉 세팅

#10 [#9] github 브랜치 네임 자동 생성
  .github/workflows/create-branch.vml
Labels: 🎉 세팅

#25 #21 PR 시 테스트 진행 테스트
  README.md
Labels: 🎉 세팅

#27 #26 폴더구조 및 리드미 작성
  src/components/README.md
  src/hooks/README.md
  src/layout/README.md
  src/pages/README.md
  src/router/README.md
  src/service/README.md
  src/styles/README.md
  src/utils/README.md
Labels: 🎉 세팅

#30 #28 리드미 작성
  README.md
  package-lock.json
  package.json
Labels: 📝 문서, 🎉 세팅

#31 #29 리드미 배포 내용 추가
  README.md
Labels: 📝 문서

#33 #32 리드미 테스트
  README.md
Labels: 📝 문서

#40 📝 테스트 중 입니다.
  README.md
Labels: 📝 문서

#46 📝 테스트입니다.
  src/pages/README.md
Labels: 📝 문서

#38 📝 : README.md 테스트
  src/styles/README.md
Labels: 📝 문서

#54 #53 stylelint 패키지 추가
  package-lock.json
  package.json
Labels: 🎉 세팅, 🚨 긴급, 📦 패키지

#51 📝 PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 문서

#57 #52 스타일 초기화 세팅
  .eslintrc.js
  .github/workflows/test.yml
  .prettierrc.json
  .stylelintrc.json
  .vscode/settings.json
  README.md
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/styles/normalize.css
  src/styles/reset.css
Labels: 🐛 버그, 💄 스타일, 💬 논의 필요, 📦 패키지

#59 📝 README.md 수정
  README.md
Labels: 📝 문서

#61 #56 HTTP 모의 요청(REST client)
  example.http
Labels: 📝 문서

#64 #62 http 요청 함수
  .env
  src/hooks/README.md
  src/hooks/useApiAction.js
  src/hooks/useFetchData.js
  src/pages/rollingList/Test.jsx
  src/service/api.js
Labels: ✨ 기능, 🧪 테스트, 🔥 우선순위 높음, 🔒 보안, 📡 API

#66 Feature/#65 global style 및 theme 설정
  public/index.html
  src/index.jsx
  src/styles/reset.css
  src/styles/theme.js
Labels: 🎉 세팅

#68 #67 http 요청 함수 버그 수정
  src/pages/rollingList/Test.jsx
  src/service/api.js
Labels: 🐛 버그, 🔍 검토 필요, 📡 API

#76 #75 � jsx파싱에러관련 eslintrc.js파일에서 module.exports에 해당옵션 추가
  .eslintrc.js
Labels: 🚨 긴급, 🔥 우선순위 높음

#73 #72 기본 라우터 세팅
  package-lock.json
  package.json
  src/App.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/MessagesAdd/MessagesAddPage.jsx
  src/pages/MessagesEdit/MessagesEditPage.jsx
  src/pages/MessagesList/MessagesListPage.jsx
  src/pages/NotFound/NotFoundPage.jsx
  src/pages/RecipientsAdd/RecipientsAddPage.jsx
  src/pages/RecipientsList/RecipientsListPage.jsx
  src/pages/RecipientsList/Test.jsx
  src/router/Content.jsx
Labels: ❓ 질문, ✨ 기능, 📦 패키지, 📰 페이지

#78 #70 아바타 기능 구현
  package-lock.json
  package.json
  src/components/TotalMessage/TotalMessage.jsx
  src/components/TotalMessage/TotalMessage.styles.js
Labels: 🎉 세팅, 💄 스타일, ✨ 기능, 📁 컴포넌트

#79 Feature/#69 공통컴포넌트 Input, Textarea, Dropdown, TextField
  package-lock.json
  public/index.html
  src/assets/icon-arrow_down.svg
  src/assets/icon-arrow_top.svg
  src/assets/icon-share-24.svg
  src/components/TextField/Dropdown.jsx
  src/components/TextField/Input.jsx
  src/components/TextField/Input.styles.js
  src/components/TextField/InputTest.jsx
  src/components/TextField/TextField.jsx
  src/components/TextField/Textarea.jsx
  src/styles/README.md
  src/styles/normalize.css
  src/styles/reset.css
  src/styles/theme.js
Labels: ✨ 기능, ⏸️ 보류, 📁 컴포넌트

#83 ✨ Outlined 공통컴포넌트 작업 추가
  src/components/Outlined/Outlined.jsx
  src/components/Outlined/Outlined.styles.js
Labels: ✨ 기능, 📁 컴포넌트

#85 #84 ✨ 공통 컴포넌트 - ArrowButton 작업
  src/components/ArrowButton/ArrowButton.jsx
  src/components/ArrowButton/ArrowButton.styles.js
Labels: ✨ 기능, 📁 컴포넌트

#87 #86 ✨ 공통컴포넌트 - Logo 작업
  src/assets/RollingLogo.svg
  src/components/Logo/Logo.jsx
  src/components/Logo/Logo.styles.js
Labels: ✨ 기능, 📁 컴포넌트

#90 #88 ✨ 공통컴포넌트 - Profile
  src/assets/default_profile.svg
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.styles.js
Labels: ✨ 기능, 📁 컴포넌트

#89 #81 ✨ 텍스트필드 유효성 검사 커스텀 훅 기능 구현
  src/hooks/useInputValidation.js
  src/pages/MessagesAdd/MessagesAddPage.jsx
Labels: ✨ 기능, ⏸️ 보류, 📁 컴포넌트

#95 #71 롤링 카드 컴포넌트 제작
  src/assets/RecipientsList/RecipientsCard/bg-polygon-triangle.svg
  src/pages/RecipientsList/RecipientsCard.jsx
  src/pages/RecipientsList/RecipientsCard.styles.js
  src/pages/RecipientsList/RecipientsListPage.jsx
Labels: ✨ 기능, 📁 컴포넌트

#98 Feature/#97 글로벌 스타일 선언하기
  src/App.jsx
  src/index.jsx
  src/styles/GlobalStyles.js
  src/styles/normalize.css
  src/styles/reset.css
  src/styles/theme.js
Labels: 🎉 세팅, 💄 스타일

#102 Feature/#100 공통 컴포넌트 emoji badge
  package-lock.json
  package.json
  src/components/Badge/EmojiBadge.jsx
  src/components/Badge/EmojiBadge.styles.js
  src/components/Badge/EmojiBadgeTest.jsx
Labels: ✨ 기능, 📁 컴포넌트

#106 #105 반응형 수치값 조정
  src/styles/GlobalStyles.js
Labels: 💄 스타일, 🚨 긴급, 🔥 우선순위 높음

#103 #101 ✨ 공통컴포넌트 - Badge
  src/components/Badge/Badge.jsx
  src/components/Badge/Badge.styles.js
Labels: ✨ 기능, 📁 컴포넌트

#108 #107 디바이스 타입 감지 커스텀 훅
  src/hooks/useDeviceType.js
Labels: ✨ 기능

#99 #92 ✨ 공통컴포넌트 - TabToggle 작업
  src/components/TabToggle/TabToggle.jsx
  src/components/TabToggle/TabToggle.styles.js
Labels: ✨ 신규 기능, 📁 컴포넌트

#115 Feature/#104 공통 컴포넌트 modal
  package-lock.json
  package.json
  src/components/Modal/Modal.styles.js
  src/components/Modal/ModalTest.js
  src/components/Modal/StyledModal.jsx
  src/components/TextField/Input.styles.js
Labels: 📁 컴포넌트

#109 #96 롤링 리스트 컴포넌트 개발
  package-lock.json
  package.json
  src/pages/RecipientsList/RecipientsCard.styles.js
  src/pages/RecipientsList/RecipientsList.jsx
  src/pages/RecipientsList/RecipientsList.styles.js
  src/pages/RecipientsList/RecipientsListPage.jsx
Labels: ✨ 신규 기능, 🧪 테스트, 📁 컴포넌트

#116 #112 생성일 날짜 변환 유틸리티 함수
  src/utils/dateConversion.js
Labels: ✨ 신규 기능, 🔨유틸리티

#120 #110 유저 정보 컴포넌트
  src/pages/MessagesList/MessagesHeader.jsx
  src/pages/MessagesList/MessagesHeader.styles.js
Labels: ✨ 신규 기능, 📁 컴포넌트

#123 #122 디바이스 감지 훅 터미널 에러 수정
  src/hooks/useDeviceType.js
Labels: 🐛 버그, 🔄 커스텀 훅

#117 ✨ 프로필 이미지 선택 기능
  src/components/InputFile/InputFile.jsx
  src/components/InputFile/InputFile.styles.js
  src/service/api.js
Labels: 💄 스타일, ✨ 신규 기능, 📁 컴포넌트

#128 💄버튼컴포넌트 스타일 변수식으로 변경
  src/components/Button/Button.styles.js
Labels: 💄 스타일

#134 🔨 메세지 헤더 날짜 표시 노출 여부
  src/pages/MessagesList/MessagesHeader.jsx
Labels: 📁 컴포넌트

#139 ✨ 테마 컬러와 폰트 쉽게 쓰는 유틸 함수 기능!
  src/pages/RecipientsList/RecipientsList.jsx
  src/utils/themeUtils.js
Labels: ✨ 신규 기능, 🚨 긴급, 🔨유틸리티

#137 #127 메시지 카드 컴포넌트
  src/assets/icon-delete.svg
  src/assets/icon-edit.svg
  src/components/Line/Line.styles.js
  src/components/TextField/Textarea.jsx
  src/pages/MessagesList/CreatedAt.styles.js
  src/pages/MessagesList/MessageCard.jsx
  src/pages/MessagesList/MessageCard.styles.js
  src/pages/MessagesList/MessagesHeader.jsx
  src/pages/MessagesList/MessagesHeader.styles.js
  src/pages/MessagesList/MessagesListPage.jsx
  src/pages/MessagesList/StyledCreatedAt.styles.js
  src/pages/MessagesList/StyledTextarea.styles.js
Labels: ✨ 신규 기능, 🔍 검토 필요, 🧪 테스트, 📁 컴포넌트

#142 #136 Outlined 컴포넌트의 스타일컴포넌트 변수사용시 $ 누락문제 수정
  src/components/Outlined/Outlined.styles.js
Labels: 🐛 버그, 🔨수정해주세요

#144 #126 메시지 생성하기 페이지
  package-lock.json
  package.json
  src/components/InputFile/InputFile.jsx
  src/pages/MessagesAdd/MessagesAddPage.jsx
  src/pages/MessagesAdd/MessagesAddPage.styles.js
Labels: 💄 스타일, ✨ 신규 기능, 📁 컴포넌트

#140 Feature/#113 공통 컴포넌트 input 수정 요청
  package-lock.json
  package.json
  src/components/Button/Button.jsx
  src/components/TextField/CommonInput.styles.js
  src/components/TextField/Dropdown.jsx
  src/components/TextField/Dropdown.styles.js
  src/components/TextField/Input.jsx
  src/components/TextField/Input.styles.js
  src/components/TextField/InputTest.jsx
Labels: ♻️ 리팩토링

#145 Feature/#141 theme 레이어 스타일 블러 쉐도우 inner쉐도우 레이어쉐도우
  package-lock.json
  src/styles/theme.js
  src/utils/themeUtils.js
Labels: 💄 스타일, 💫 업데이트

#121 🚀 Toast스타일, 기능 컴포넌트 입니다.
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
  src/assets/close.svg
  src/assets/completed.svg
  src/assets/icon-close.svg
  src/assets/icon-completed.svg
  src/components/toast/CopyUrl.jsx
  src/components/toast/Toast.Styles.js
  src/components/toast/Toast.jsx
  src/components/toast/ToastMessages.jsx
  src/pages/HomePage/HomePage.jsx
  src/pages/README.md
  src/pages/RecipientsList/RecipientsList.jsx
  src/styles/normalize.css
Labels: 📁 컴포넌트

#148 #147 롤링 카드 이모지 라벨 연결
  src/components/Badge/EmojiBadge.jsx
  src/components/Badge/EmojiBadge.styles.js
  src/pages/RecipientsList/RecipientsCard.jsx
  src/router/Content.jsx
Labels: 💄 스타일, 💫 업데이트

#154 #151 radio 선택 기능
  src/assets/icon-checked.svg
  src/components/BackgroundSelector/BackgroundSelector.jsx
  src/components/BackgroundSelector/RadioCard.jsx
  src/components/BackgroundSelector/RadioCard.styles.js
  src/components/TabToggle/TabToggle.jsx
  src/components/TabToggle/TabToggle.styles.js
  src/pages/MessagesAdd/MessagesAddPage.styles.js
Labels: 💄 스타일, ✨ 신규 기능, 📁 컴포넌트

#167 #157 메세지 리스트 스타일 컴포넌트 제작
  example.http
  src/assets/MessagesList/icon-add.svg
  src/components/Button/Button.jsx
  src/components/MessagesCardList/MessageCard.jsx
  src/components/MessagesCardList/MessageCard.styles.js
  src/components/MessagesCardList/MessageCardAddItem.jsx
  src/components/MessagesCardList/MessageCardList.jsx
  src/components/MessagesCardList/MessageCardList.styles.js
  src/components/MessagesCardList/MessagesHeader.jsx
  src/components/MessagesCardList/MessagesHeader.styles.js
  src/components/MessagesCardList/StyledCreatedAt.styles.js
  src/components/MessagesCardList/StyledTextarea.styles.js
  src/components/Modal/StyledModal.jsx
  src/hooks/useFetchData.js
  src/index.jsx
  src/pages/MessagesEdit/Test_MessagesEditPage.jsx
  src/pages/MessagesList/MessagesListPage.jsx
  src/pages/MessagesList/MessagesListPage.styles.js
  src/router/Content.jsx
  src/service/api.js
  src/styles/GlobalStyles.js
Labels: ✨ 신규 기능, 📁 컴포넌트, 🔄 커스텀 훅, 💫 업데이트

#166 #163 메세지 작성하기 컨테이너 작업
  src/components/InputFile/InputFile.jsx
  src/components/InputFile/InputFile.styles.js
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.styles.js
  src/components/TextField/CommonInput.styles.js
  src/components/TextField/Dropdown.jsx
  src/components/TextField/Dropdown.styles.js
  src/components/TextField/Input.jsx
  src/components/TextField/TextField.jsx
  src/pages/MessagesAdd/MessagesAddPage.jsx
  src/pages/MessagesAdd/MessagesAddPage.styles.js
Labels: 💄 스타일, ♻️ 리팩토링

#182 #182 전체 재조정 (현재 작업 영향 없음)
  .cspell.json
  src/App.jsx
  src/router/Content.jsx
  src/styles/common.css
  src/styles/fontStyle.js
  src/styles/reset.css
  src/styles/theme_mode.js
Labels: 💄 스타일, 🚨 긴급, ⏸️ 보류, 💬 논의 필요, ♻️ 리팩토링

#184 Feature/#183 전체 디자인 시스템 변경
  src/App.jsx
  src/components/ArrowButton/ArrowButton.styles.js
  src/components/BackgroundSelector/RadioCard.jsx
  src/components/Badge/Badge.styles.js
  src/components/Badge/EmojiBadge.styles.js
  src/components/Button/Button.styles.js
  src/components/InputFile/InputFile.styles.js
  src/components/Line/Line.styles.js
  src/components/MessagesCardList/MessageCard.styles.js
  src/components/MessagesCardList/MessagesHeader.styles.js
  src/components/MessagesCardList/StyledCreatedAt.styles.js
  src/components/MessagesCardList/StyledTextarea.styles.js
  src/components/Outlined/Outlined.styles.js
  src/components/Profile/Profile.styles.js
  src/components/TabToggle/TabToggle.styles.js
  src/components/TextField/CommonInput.styles.js
  src/components/TextField/Dropdown.styles.js
  src/components/TotalMessage/TotalMessage.styles.js
  src/components/toast/Toast.Styles.js
  src/index.jsx
  src/pages/MessagesAdd/MessagesAddPage.styles.js
  src/pages/MessagesList/MessagesListPage.styles.js
  src/pages/RecipientsList/RecipientsCard.styles.js
  src/styles/GlobalStyles.js
  src/styles/blurStyles.js
  src/styles/colors.js
  src/styles/common.css
  src/styles/fontStyles.js
  src/styles/reset.css
  src/styles/shadowStyles.js
  src/styles/theme.js
  src/styles/theme_mode.js
  src/styles/theme_old.js
  src/utils/themeUtils.js
Labels: 💄 스타일, 🚨 긴급

#170 #156 아웃라인버튼 경고문구 크기단위 관련 수정
  src/components/Badge/Badge.styles.js
  src/components/Outlined/Outlined.jsx
  src/components/Outlined/Outlined.styles.js
  src/components/Profile/Profile.styles.js
Labels: 🐛 버그, 💄 스타일
